Repository shopl/shopl-design-guide-android, pull requests merged in 2025-09, with the labels that each got.

#99 [SH-13195] [Android] SDGSimpleTextInput - VisualTransformation 옵션 추가
  sdg/src/main/java/com/shopl/sdg/component/text_input/simple/SDGSimpleTextInput.kt
  sdg/src/main/java/com/shopl/sdg/component/util/simple_text_input/SDGSimpleTextInput.kt
Labels: update

#98 [SH-13192] [Android] 사용하지 않는 Spacing 제거
  sdg-common/src/main/java/com/shopl/sdg_common/foundation/spacing/SDGSpacing.kt
  sdg/src/main/java/com/shopl/sdg/template/popup/list/anatomy/SDGListPopupBody.kt
Labels: update

#102 [SH-13227] [Android] SDGColor > Special RP 추가
  sdg-common/src/main/java/com/shopl/sdg_common/foundation/SDGColor.kt
Labels: update

#107 [SH-13271] [Android] SDGColor > Special YG 추가
  sdg-common/src/main/java/com/shopl/sdg_common/foundation/SDGColor.kt
Labels: update

#108 [SH-13276] [Android] Icon Label Ripple 효과 제거
  sdg/src/main/java/com/shopl/sdg/component/icon_label/SDGIconLabel.kt
  sdg/src/main/java/com/shopl/sdg/component/icon_label/SDGIconLabelPreviewProvider.kt
Labels: update

#109 [SH-13286] Clickable hasRipple default 값을 false로 변경
  sdg-common/src/main/java/com/shopl/sdg_common/ext/ModifierExt.kt
Labels: update

#112 [SH-13454] Template > Form > Select Form > Typography 변경
  sdg/src/main/java/com/shopl/sdg/template/form/SDGForm.kt
Labels: update

#113 버전 업데이트 1.1.8
  build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt
Labels: patch

#115 버전 업데이트 1.1.9
  build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt
Labels: patch, fast-track

#116 [SH-13477] SDGAsyncImage LocalInspectionMode 추가
  sdg-common/src/main/java/com/shopl/sdg_common/ui/components/SDGAsyncImage.kt
Labels: update

#117 [SH-13478] [Android] Line Fixed Tab 디자인 가이드 최신화
  sdg/src/main/java/com/shopl/sdg/component/tab/SDGLineFixedTab.kt
Labels: update

#120 [SH-13548] [Android] 가이드 최신화
  sdg/src/main/java/com/shopl/sdg/component/empty_icon/SDGBasicEmpty.kt
Labels: update
