Repository shopl/shopl-design-guide-android, pull requests merged in 2025-06, with the labels that each got.

#17 [SH-11547] SDG Component > Indicator > Text Indicator
  sdg/src/main/java/com/shopl/sdg/component/indicator/SDGTextIndicator.kt
Labels: add

#19 [SH-11598] SDG Template > Multi Calendar 단일 선택 옵션 기능 수정
  sdg/src/main/java/com/shopl/sdg/template/multi_calendar/SDGMultiCalendar.kt
Labels: update

#20 [SH-11605] SDG Template > Form > Selected Input 아이콘 정보 추가
  sdg/src/main/java/com/shopl/sdg/template/form/SDGForm.kt
Labels: update

#21 [SH-11598] SDG Template > Multi Calendar 단일 선택 옵션 기능 수정 - 일별 날짜 표기 수정
  sdg/src/main/java/com/shopl/sdg/template/multi_calendar/SDGMultiCalendar.kt
Labels: update

#22 [SH-11557] SDG Template > Form > Simple Input 추가 - 키보드 옵션 추가
  sdg/src/main/java/com/shopl/sdg/template/form/SDGSimpleInputForm.kt
Labels: update

#23 [SH-11645] 릴리즈 drafter 및 태깅 자동화
  .github/release-drafter-config.yml
  .github/workflows/release-drafter.yml
Labels: document

#24 [SH-11646] PR 컨벤션 자동화
  .github/workflows/create_pr.yml
Labels: document

#25 [SH-11519] Type, Size 등을 디자인 시스템 요소 구현부와 분리
  sdg/src/main/java/com/shopl/sdg/component/button/bottom/SDGBottomButton.kt
  sdg/src/main/java/com/shopl/sdg/component/button/box/SDGBoxButton.kt
  sdg/src/main/java/com/shopl/sdg/component/button/box/SDGBoxButtonSize.kt
  sdg/src/main/java/com/shopl/sdg/component/button/box/SDGBoxButtonType.kt
  sdg/src/main/java/com/shopl/sdg/component/button/capsule/SDGCapsuleButton.kt
  sdg/src/main/java/com/shopl/sdg/component/button/capsule/SDGCapsuleButtonSize.kt
  sdg/src/main/java/com/shopl/sdg/component/button/capsule/SDGCapsuleButtonType.kt
  sdg/src/main/java/com/shopl/sdg/component/button/ghost/SDGGhostButton.kt
  sdg/src/main/java/com/shopl/sdg/component/button/ghost/SDGGhostButtonSize.kt
  sdg/src/main/java/com/shopl/sdg/component/checkbox/SDGCheckBox.kt
Labels: update

#27 [SH-11665] [Android] SDG Component > Simple Input/ Fixed Input -> Simple Text Input/Fixed Text Input으로 네이밍 변경
  sdg-common/src/main/java/com/shopl/sdg_common/util/KeyboardUtil.kt
  sdg/src/androidTest/java/com/shopl/sdg/ExampleInstrumentedTest.kt
  sdg/src/main/java/com/shopl/sdg/component/search_bar/SearchBar.kt
  sdg/src/main/java/com/shopl/sdg/component/text_input/InputState.kt
  sdg/src/main/java/com/shopl/sdg/component/text_input/SDGInput.kt
  sdg/src/main/java/com/shopl/sdg/component/text_input/fixed/SDGFixedTextInput.kt
  sdg/src/main/java/com/shopl/sdg/component/text_input/simple/SDGSimpleTextInput.kt
  sdg/src/main/java/com/shopl/sdg/component/text_input/simple/SDGSimpleTextInputType.kt
  sdg/src/main/java/com/shopl/sdg/component/text_input/underline/SDGUnderlineInput.kt
  sdg/src/main/java/com/shopl/sdg/component/util/simple_text_input/SDGSimpleTextInput.kt
  sdg/src/main/java/com/shopl/sdg/template/form/SDGForm.kt
  sdg/src/main/java/com/shopl/sdg/template/form/SDGSimpleInputForm.kt
  sdg/src/test/java/com/shopl/sdg/ExampleUnitTest.kt
Labels: update

#28 [SH-11722] [Android] IOText Deprecated 처리
  sdg-common/src/main/java/com/shopl/sdg_common/ui/components/IOText.kt
Labels: document

#30 [SH-11747] [Android] SDG Com > Thumbnails 신규
  sdg-resource/src/main/res/drawable/ic_common_photo.xml
  sdg-resource/src/main/res/drawable/ic_remove_m.xml
  sdg/src/main/java/com/shopl/sdg/component/thumbnail/Thumbnails.kt
Labels: add
