Repository shopl/shopl-design-guide-android, pull requests merged in 2025-07, with the labels that each got.

#32 update version to 1.0.3
  build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt
Labels: minor

#34 [SH-11747] [Android] SDG Com > Thumbnails 신규
  sdg/src/main/java/com/shopl/sdg/component/thumbnail/SDGThumbnails.kt
Labels: add

#39 [SH-11937] [Android] Spacing 재정의
  sdg-common/src/main/java/com/shopl/sdg_common/foundation/spacing/SDGGap.kt
  sdg-common/src/main/java/com/shopl/sdg_common/foundation/spacing/SDGMargin.kt
  sdg-common/src/main/java/com/shopl/sdg_common/foundation/spacing/SDGPadding.kt
  sdg-common/src/main/java/com/shopl/sdg_common/foundation/spacing/SDGSizeUnit.kt
  sdg-common/src/main/java/com/shopl/sdg_common/foundation/spacing/SDGSpacing.kt
Labels: update

#42 1.0.5 버전 업데이트
  build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt
Labels: patch

#43 [SH-11942] SDG 배포 상태 Polling 시간 조정
  .github/workflows/auto-deploy.yml
Labels: document

#46 1.0.6 버전 업데이트
  build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt
Labels: patch

#54 1.0.7 버전 업데이트
  build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt
Labels: patch

#58 1.0.8 버전 업데이트
  build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt
Labels: patch

#59 Coil 네트워킹 라이브러리 추가
  gradle/libs.versions.toml
  sdg-common/build.gradle.kts
Labels: document

#61 [SH-12052] [Android] SDGColor > Special CG 추가
  sdg-common/src/main/java/com/shopl/sdg_common/foundation/SDGColor.kt
Labels: update

#62 1.0.9 버전 업데이트
  build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt
Labels: patch

#60 [SH-11979] [Android] Number Picker 신규 컴포넌트 추가
  app/build.gradle.kts
  app/src/main/java/com/shopl/sdg/MainActivity.kt
  sdg-common/src/main/java/com/shopl/sdg_common/ui/components/NumberPicker.kt
  sdg/src/main/java/com/shopl/sdg/component/calendar/SDGCalendarDay.kt
  sdg/src/main/java/com/shopl/sdg/component/number_picker/SDGNumberPicker.kt
Labels: add

#67 [SH-12090] [Android] SDG Component > Ghost Button 레거시 수정
  sdg/src/main/java/com/shopl/sdg/component/button/ghost/SDGGhostButton.kt
  sdg/src/main/java/com/shopl/sdg/component/button/ghost/SDGGhostButtonSize.kt
  sdg/src/main/java/com/shopl/sdg/component/util/button/ghost/SDGGhostButton.kt
  sdg/src/main/java/com/shopl/sdg/template/multi_calendar/SDGMultiCalendar.kt
Labels: update

#64 [SH-12068] [Android] List Popup > List Bottom Sheet 추가
  sdg-common/src/main/java/com/shopl/sdg_common/foundation/spacing/SDGSpacing.kt
  sdg/src/main/java/com/shopl/sdg/template/popup/SDGListPopup.kt
  sdg/src/main/java/com/shopl/sdg/template/popup/list/anatomy/SDGListBottomSheet.kt
  sdg/src/main/java/com/shopl/sdg/template/popup/list/anatomy/SDGListPopupBody.kt
  sdg/src/main/java/com/shopl/sdg/template/util/list_popup_item_ui_state/SDGListPopupItemUiState.kt
Labels: add

#73 1.1.0 버전 업데이트
  build-logic/src/main/kotlin/com/shopl/sdg/build_logic/PublishingConfig.kt
Labels: minor

#75 [SH-12209] [Android] SDG > Ghost Button 타이포그라피 폰트 두께 옵션 추가
  sdg/src/main/java/com/shopl/sdg/component/button/SDGButtonFontWeight.kt
  sdg/src/main/java/com/shopl/sdg/component/button/ghost/SDGGhostButton.kt
  sdg/src/main/java/com/shopl/sdg/component/button/ghost/SDGGhostButtonIconSize.kt
  sdg/src/main/java/com/shopl/sdg/component/util/button/ghost/SDGGhostButton.kt
Labels: update

#76 [SH-12139] [Android] SDG Tem > Popup : 유형 분류 및 가이드 업데이트 대응
  sdg/src/main/java/com/shopl/sdg/template/popup/center/SDGCenterPopup.kt
  sdg/src/main/java/com/shopl/sdg/template/popup/center/SDGCenterPopupButton.kt
  sdg/src/main/java/com/shopl/sdg/template/popup/center/SDGCenterPopupButtonOption.kt
  sdg/src/main/java/com/shopl/sdg/template/popup/center/confirm/SDGConfirmCenterPopup.kt
  sdg/src/main/java/com/shopl/sdg/template/popup/center/delete/SDGDeleteCenterPopup.kt
  sdg/src/main/java/com/shopl/sdg/template/popup/center/info/SDGInfoCenterPopup.kt
  sdg/src/main/java/com/shopl/sdg/template/popup/center/input/SDGInputCenterPopup.kt
Labels: update

#77 [SH-12247] [Android] SDG Template > Check Option List Item -> Check Option Label로 업데이트
  sdg/src/main/java/com/shopl/sdg/component/check_option/SDGCheck.kt
  sdg/src/main/java/com/shopl/sdg/template/check_option_label/SDGCheckOptionLabel.kt
  sdg/src/main/java/com/shopl/sdg/template/check_option_label/SDGCheckOptionLabelSize.kt
Labels: update
